# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - aws-cli/setup:
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME 
          aws-region: AWS_REGION 
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME 
          role-arn: arn:aws:iam::457416323948:user/udagram22cli 

workflows:
  example-workflow:
    jobs:
      - example-job