# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
  aws-s3: circleci/aws-s3@3.0.0
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
  node: circleci/node@5.0.2
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - aws-elastic-beanstalk/setup
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID 
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY 
          aws-region: AWS_REGION 
      # - aws-elastic-beanstalk/setup:
      - run:
          name: install angular cli globally
          command: |
           npm install -g @angular/cli
      - run:
          name: Front-End Install
          command: |
            cd ./udagram/udagram-frontend && npm install && npm run build 
      - run:
          name: Back-End Install
          command: |
            cd ./udagram/udagram-api && npm install && npm run build           
      - run:
          name: Front-End build
          command: |
            cd ./udagram/udagram-frontend && npm run build 
      - run:
          name: Back-End build
          command: |
            cd ./udagram/udagram-api && npm run build 
      - run:
          name: Front-End test-lint
          command: |
            cd ./udagram/udagram-frontend && npm run test
      - run:
          name: Front-End deploy
          command: |
            cd ./udagram/udagram-frontend && npm run deploy      
                  - eb/setup:
      - run:
          name: EB intitialization
          command: |
            apt-get -y -qq update
            apt-get install python3-pip python3-dev build-essential
            pip3 install awsebcli
            eb init 
            eb use EB_ENV_NAME
            eb status   
      - run:
          name: Back-End deploy
          command: |
            cd ./udagram/udagram-api && npm run deploy 
            
              

