# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
  node: circleci/node@5.0.2
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  aws-cli-installation:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - aws-cli/setup:
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME 
          aws-region: AWS_REGION 
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME 
          role-arn: arn:aws:iam::457416323948:user/udagram22cli 
  npm-installation:
    docker:
      - image: cimg/base:stable
    steps:
      - node/install
      - checkout
      - run:
          name: Front-End Install
          command: |
            cd ./udagram/udagram-frontend && npm install && npm run build
      - run:
          name: Back-End Install
          command: |
            cd ./udagram/udagram-api && npm install && npm run build 
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Front-End build
          command: |
            cd ./udagram/udagram-frontend && npm run build
            
      - run:
          name: Back-End build
          command: |
            cd ./udagram/udagram-api && npm run build 
                      
workflows:
  udagram22app:
    jobs:
      - aws-cli-installation
      - npm-installation
      - build